apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name:mydeployment
spec:
  selector:
    matchLabels:
      app: myspringbootapp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      containers:
        - name: myspringbootapp
          image: mahabendaoud/cicd:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 9099 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: myservice
spec:
  selector:
    app: myspringbootapp
  ports:
    - nodePort: 30036
      port: 80 # The port that the service is running on in the cluster
      targetPort: 9099 # The port exposed by the service
  type: LoadBalancer # type of the service.
